### PR TITLE
* fix scripts

### PR DESCRIPTION
**Pull request by oxy1914**
tried to make it work on my mac, some progress. but  flatten.pl is missed
./prn: line 6: flatten.pl: command not found

### CODE REVIEW

**Comment by leobru** [comment]
How about adding the current directory in your path?

**Comment by leobru** [comment]
BESM6_PATH=${BESM6_PATH:-build}

No. When BESM6_PATH is not set, if defaults to ~/.besm6 and I like that.

**Comment by oxy1914** [comment]
> How about adding the current directory in your path?

not everybody has . in the path.
i think the repo when builds must rely only on local scripts.
btw  where is  flatten.pl ?

**Comment by oxy1914** [comment]
> BESM6_PATH=${BESM6_PATH:-build}
> 
> No. When BESM6_PATH is not set, if defaults to ~/.besm6 and I like that.

but what the compile script does it removes the disk, isn't it scary to have a working disk removed in ~/.besm6 even if build fails?

**Comment by leobru** [comment]
Please fetch.

**Pull request closed without merging**
